version: "3.8"

services:

  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=filmdb_users
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"